# Generated by Django 4.2 on 2023-06-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_imge_profile_image_ehrprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
