# Generated by Django 4.2 on 2023-06-02 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHRHospitalStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('workfor', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=110)),
                ('dob', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EHRProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
