# Generated by Django 4.2 on 2023-06-02 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_ehrhospitalstaffprofile_delete_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('workfor', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='pics')),
                ('medicalInsutance', models.CharField(max_length=100)),
                ('VisionInsurance', models.CharField(max_length=100)),
                ('DentalInsurance', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EHRHospitalStaffProfile',
        ),
    ]
