# Generated by Django 4.2 on 2023-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_hospitalstaffprofile_delete_ehrhospitalstaffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentOfPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitType', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Provider', models.CharField(max_length=30)),
                ('AppointmentDate', models.DateField()),
            ],
        ),
    ]
