# Generated by Django 4.2 on 2023-06-02 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0008_appointmentofperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentOfPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitType', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Provider', models.CharField(max_length=30)),
                ('AppointmentDate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='appointmentOfPerson',
        ),
    ]
