# Generated by Django 4.2 on 2023-06-13 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0012_createnewpatient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createNewPatient',
            new_name='newPatientCreation',
        ),
    ]
