# Generated by Django 4.2 on 2023-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_createnewpatient_delete_newpatientcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnHospitalStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_email', models.BinaryField()),
            ],
        ),
    ]
