# Generated by Django 4.2 on 2023-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_enhospitalstaffprofile_delete_ehospitalstaffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHospitalStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_email', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='EnHospitalStaffProfile',
        ),
    ]
