# Generated by Django 4.2 on 2023-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_ehospitalstaffprofile_delete_enhospitalstaffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnHospitalStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_email', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='EHospitalStaffProfile',
        ),
    ]
