# Generated by Django 4.2 on 2023-06-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_enhospitalstaffprofile_delete_ehospitalstaffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enhospitalstaffprofile',
            name='encryption_key',
        ),
    ]
