# Generated by Django 4.2 on 2023-06-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_remove_enhospitalstaffprofile_encryption_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeHospitalStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_email', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='EnHospitalStaffProfile',
        ),
    ]
