# Generated by Django 4.2 on 2023-06-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_createnewpatient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewpatient',
            name='dob',
            field=models.DateField(),
        ),
    ]
