# Generated by Django 4.2 on 2023-06-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_rename_createnewpatients_createpatient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createPatient',
            new_name='createNewPatient',
        ),
    ]
