# Generated by Django 4.2 on 2023-06-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_rename_createpatient_createnewpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='createPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pics')),
                ('first_name', models.BinaryField()),
                ('last_name', models.BinaryField()),
                ('dateOfBirth', models.DateField()),
                ('sex', models.BinaryField()),
                ('nic', models.BinaryField()),
                ('mobile_number', models.BinaryField()),
                ('email', models.BinaryField()),
                ('address', models.BinaryField()),
                ('primary_phone', models.BinaryField()),
                ('secondary_phone', models.BinaryField()),
            ],
        ),
    ]
