# Generated by Django 4.2 on 2023-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_createpatient_delete_createnewpatient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createPatient',
        ),
        migrations.RenameField(
            model_name='createnewpatient',
            old_name='dateOfBirth',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='nic',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='primary_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='secondary_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='createnewpatient',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
