# Generated by Django 4.2 on 2023-06-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_createpatient_delete_createnewpatient'),
    ]

    operations = [
    ]
