# Generated by Django 4.2 on 2023-06-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_createpatient_delete_createnewpatient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createPatient',
            new_name='newCreatePatient',
        ),
    ]
