# Generated by Django 4.2 on 2023-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_rename_createpatient_newcreatepatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcreatepatient',
            name='first_name',
            field=models.BinaryField(),
        ),
    ]
