# Generated by Django 4.2 on 2023-06-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_alter_createnewpatient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createnewpatient',
            name='password',
        ),
    ]
