# Generated by Django 4.2 on 2023-06-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_remove_createnewpatient_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createNewPatient',
        ),
    ]
