# Generated by Django 4.2 on 2023-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_createappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='createNewAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.BinaryField()),
                ('patient_id', models.BinaryField()),
                ('date', models.DateField()),
                ('visit_type', models.BinaryField()),
                ('location', models.BinaryField()),
                ('comments', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='createAppointment',
        ),
    ]
