# Generated by Django 4.2 on 2023-06-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_createnewappointment_delete_createappointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createNewAppointment',
            new_name='createAppointment',
        ),
    ]
