# Generated by Django 4.2 on 2023-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0047_createprescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='createMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id_num', models.BinaryField()),
                ('patient_id_num', models.BinaryField()),
                ('patient_name', models.BinaryField()),
                ('date', models.DateField()),
                ('location', models.BinaryField()),
                ('message', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
            ],
        ),
    ]
