# Generated by Django 4.2 on 2023-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0048_createmedicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='createMedicalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id_num', models.BinaryField()),
                ('patient_id_num', models.BinaryField()),
                ('service_detail', models.BinaryField()),
                ('date', models.DateField()),
                ('location', models.BinaryField()),
                ('payment_amount', models.BinaryField()),
                ('payment_status', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
            ],
        ),
    ]
