# Generated by Django 4.2 on 2023-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0049_createmedicalbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='createMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id_num', models.BinaryField()),
                ('patient_id_num', models.BinaryField()),
                ('medicationName', models.BinaryField()),
                ('dose', models.BinaryField()),
                ('frequency', models.BinaryField()),
                ('date', models.DateField()),
                ('location', models.BinaryField()),
                ('message', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='createReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id_num', models.BinaryField()),
                ('patient_id_num', models.BinaryField()),
                ('test_type', models.BinaryField()),
                ('date', models.DateField()),
                ('location', models.BinaryField()),
                ('message', models.BinaryField()),
            ],
        ),
    ]
