# Generated by Django 4.2 on 2023-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0050_createmedication_createreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='createNewMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id_num', models.BinaryField()),
                ('patient_id_num', models.BinaryField()),
                ('medicationName', models.BinaryField()),
                ('dose', models.BinaryField()),
                ('frequency', models.BinaryField()),
                ('date', models.DateField()),
                ('location', models.BinaryField()),
                ('message', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='createMedication',
        ),
    ]
